//>>built
(function(f,p){var d,l,m=function(){},e=function(h){for(var a in h)return 0;return 1},n={}.toString,k=function(h){return"[object Function]"==n.call(h)},g=function(h){return"[object String]"==n.call(h)},a=function(h){return"[object Array]"==n.call(h)},s=function(h,a){if(h)for(var b=0;b<h.length;)a(h[b++])},b=function(h,a){for(var b in a)h[b]=a[b];return h},c=function(h,a){return b(Error(h),{src:"dojoLoader",info:a})},B=1,C=function(){return"_"+B++},r=function(h,a,b){return ua(h,a,b,0,r)},v=this,u=
v.document,L=u&&u.createElement("DiV"),t=r.has=function(h){return k(w[h])?w[h]=w[h](v,u,L):w[h]},w=t.cache=p.hasCache;t.add=function(h,a,b,q){(void 0===w[h]||q)&&(w[h]=a);return b&&t(h)};for(var x in f.has)t.add(x,f.has[x],0,1);r.async=1;var Y=new Function("return eval(arguments[0]);");r.eval=function(h,a){return Y(h+"\r\n//# sourceURL\x3d"+a)};var q={},J=r.signal=function(h,b){var c=q[h];s(c&&c.slice(0),function(h){h.apply(null,a(b)?b:[b])})},Z=r.on=function(h,a){var b=q[h]||(q[h]=[]);b.push(a);
return{remove:function(){for(var h=0;h<b.length;h++)if(b[h]===a){b.splice(h,1);break}}}},va=[],Ha={},wa=[],T={},E=r.map={},F=[],D={},A="",y={},z={};x={};var U=0,H=function(h){var a,b,q,c;for(a in z)b=z[a],(q=a.match(/^url\:(.+)/))?y["url:"+xa(q[1],h)]=b:"*now"==a?c=b:"*noref"!=a&&(q=$(a,h,!0),y[q.mid]=y["url:"+q.url]=b);c&&c(ia(h));z={}},G=function(h){return h.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(h){return"\\"+h})},P=function(h,a){a.splice(0,a.length);for(var b in h)a.push([b,h[b],RegExp("^"+
G(b)+"(/|$)"),b.length]);a.sort(function(h,a){return a[3]-h[3]});return a},ya=function(h,a){s(h,function(h){a.push([g(h[0])?RegExp("^"+G(h[0])+"$"):h[0],h[1]])})},I=function(h){var a=h.name;a||(a=h,h={name:a});h=b({main:"main"},h);h.location=h.location?h.location:a;h.packageMap&&(E[a]=h.packageMap);h.main.indexOf("./")||(h.main=h.main.substring(2));T[a]=h},V=[],O=function(h,a,q){for(var c in h){"waitSeconds"==c&&(r.waitms=1E3*(h[c]||0));"cacheBust"==c&&(A=h[c]?g(h[c])?h[c]:(new Date).getTime()+"":
"");if("baseUrl"==c||"combo"==c)r[c]=h[c];h[c]!==w&&(r.rawConfig[c]=h[c],"has"!=c&&t.add("config-"+c,h[c],0,a))}r.baseUrl||(r.baseUrl="./");/\/$/.test(r.baseUrl)||(r.baseUrl+="/");for(c in h.has)t.add(c,h.has[c],0,a);s(h.packages,I);for(l in h.packagePaths)s(h.packagePaths[l],function(h){var a=l+"/"+h;g(h)&&(h={name:h});h.location=a;I(h)});P(b(E,h.map),F);s(F,function(h){h[1]=P(h[1],[]);"*"==h[0]&&(F.star=h)});P(b(Ha,h.paths),wa);ya(h.aliases,va);if(a)V.push({config:h.config});else for(c in h.config)a=
S(c,q),a.config=b(a.config||{},h.config[c]);h.cache&&(H(),z=h.cache,h.cache["*noref"]&&H());J("config",[h,r.rawConfig])};if(t("dojo-cdn")){var Q=u.getElementsByTagName("script");d=0;for(var K,M,aa,W;d<Q.length;){K=Q[d++];if((aa=K.getAttribute("src"))&&(W=aa.match(/(((.*)\/)|^)dojo\.js(\W|$)/i)))M=W[3]||"",p.baseUrl=p.baseUrl||M,U=K;if(aa=K.getAttribute("data-dojo-config")||K.getAttribute("djConfig"))x=r.eval("({ "+aa+" })","data-dojo-config"),U=K}}r.rawConfig={};O(p,1);t("dojo-cdn")&&((T.dojo.location=
M)&&(M+="/"),T.dijit.location=M+"../dijit/",T.dojox.location=M+"../dojox/");O(f,1);O(x,1);var ba=function(h){ja(function(){s(h.deps,za)})},ua=function(h,q,e,s,d){var k;if(g(h)){if((k=S(h,s,!0))&&k.executed)return k.result;if("dojo/i18n"===s.mid)return;throw c("undefinedModule",h);}a(h)||(O(h,0,s),h=q,q=e);if(a(h))if(h.length){e="require*"+C();for(var B,f=[],t=0;t<h.length;)B=h[t++],f.push(S(B,s));k=b(ca("",e,0,""),{injected:2,deps:f,def:q||m,require:s?s.require:r,gc:1});D[k.mid]=k;ba(k);var J=X&&
0!="sync";ja(function(){ka(k,J)});k.executed||R.push(k);da()}else q&&q();return d},ia=function(h){if(!h)return r;var a=h.require;a||(a=function(b,c,q){return ua(b,c,q,h,a)},h.require=b(a,r),a.module=h,a.toUrl=function(a){return xa(a,h)},a.toAbsMid=function(a){return la(a,h)});return a},R=[],ea=[],N={},Ja=function(h){h.injected=1;N[h.mid]=1;h.url&&(N[h.url]=h.pack||1);Ia()},fa=function(h){h.injected=2;delete N[h.mid];h.url&&delete N[h.url];e(N)&&Ka()},La=r.idle=function(){return!ea.length&&e(N)&&!R.length&&
!X},ma=function(h,a){if(a)for(var b=0;b<a.length;b++)if(a[b][2].test(h))return a[b];return 0},Aa=function(h){var a=[],b,c;for(h=h.replace(/\\/g,"/").split("/");h.length;)b=h.shift(),".."==b&&a.length&&".."!=c?(a.pop(),c=a[a.length-1]):"."!=b&&a.push(c=b);return a.join("/")},ca=function(h,a,b,c){return{pid:h,mid:a,pack:b,url:c,executed:0,def:0}},Ba=function(h,a,b,q,e,g,d,m,B){var f,r,t,J;J=/^\./.test(h);if(/(^\/)|(\:)|(\.js$)/.test(h)||J&&!a)return ca(0,h,0,h);h=Aa(J?a.mid+"/../"+h:h);if(/^\./.test(h))throw c("irrationalPath",
h);a&&(t=ma(a.mid,g));(t=(t=t||g.star)&&ma(h,t[1]))&&(h=t[1]+h.substring(t[3]));a=(W=h.match(/^([^\/]+)(\/(.+))?$/))?W[1]:"";(f=b[a])?h=a+"/"+(r=W[3]||f.main):a="";var l=0;s(m,function(a){var b=h.match(a[0]);b&&0<b.length&&(l=k(a[1])?h.replace(a[0],a[1]):a[1])});if(l)return Ba(l,0,b,q,e,g,d,m,B);if(b=q[h])return B?ca(b.pid,b.mid,b.pack,b.url):q[h];q=(t=ma(h,d))?t[1]+h.substring(t[3]):a?f.location+"/"+r:h;/(^\/)|(\:)/.test(q)||(q=e+q);return ca(a,h,f,Aa(q+".js"))},$=function(h,a,b){return Ba(h,a,T,
D,r.baseUrl,b?[]:F,b?[]:wa,b?[]:va)},Ca=function(h,a,b){return h.normalize?h.normalize(a,function(h){return la(h,b)}):la(a,b)},Da=0,S=function(h,a,b){var c,q;(c=h.match(/^(.+?)\!(.*)$/))?(q=S(c[1],a,b),5===q.executed&&!q.load&&na(q),q.load?(c=Ca(q,c[2],a),h=q.mid+"!"+(q.dynamic?++Da+"!":"")+c):(c=c[2],h=q.mid+"!"+ ++Da+"!waitingForPlugin"),h={plugin:q,mid:h,req:ia(a),prid:c}):h=$(h,a);return D[h.mid]||!b&&(D[h.mid]=h)},la=r.toAbsMid=function(h,a){return $(h,a).mid},xa=r.toUrl=function(h,a){var b=
$(h+"/x",a),c=b.url;return Ea(0===b.pid?h:c.substring(0,c.length-5))},Fa={injected:2,executed:5,def:3,result:3};M=function(h){return D[h]=b({mid:h},Fa)};var Ma=M("require"),Na=M("exports"),Oa=M("module"),ga={},oa=0,na=function(h){var a=h.result;h.dynamic=a.dynamic;h.normalize=a.normalize;h.load=a.load;return h},Pa=function(h){var a={};s(h.loadQ,function(c){var q=Ca(h,c.prid,c.req.module),g=h.dynamic?c.mid.replace(/waitingForPlugin$/,q):h.mid+"!"+q,q=b(b({},c),{mid:g,prid:q,injected:0});D[g]||Ga(D[g]=
q);a[c.mid]=D[g];fa(c);delete D[c.mid]});h.loadQ=0;var c=function(h){for(var b=h.deps||[],c=0;c<b.length;c++)(h=a[b[c].mid])&&(b[c]=h)},q;for(q in D)c(D[q]);s(R,c)},pa=function(h){r.trace("loader-finish-exec",[h.mid]);h.executed=5;h.defOrder=oa++;h.loadQ&&(na(h),Pa(h));for(d=0;d<R.length;)R[d]===h?R.splice(d,1):d++;/^require\*/.test(h.mid)&&delete D[h.mid]},Qa=[],ka=function(h,a){if(4===h.executed)return r.trace("loader-circular-dependency",[Qa.concat(h.mid).join("-\x3e")]),!h.def||a?ga:h.cjs&&h.cjs.exports;
if(!h.executed){if(!h.def)return ga;var b=h.mid,c=h.deps||[],q,g=[],e=0;for(h.executed=4;q=c[e++];){q=q===Ma?ia(h):q===Na?h.cjs.exports:q===Oa?h.cjs:ka(q,a);if(q===ga)return h.executed=0,r.trace("loader-exec-module",["abort",b]),ga;g.push(q)}r.trace("loader-run-factory",[h.mid]);b=h.def;g=k(b)?b.apply(null,g):b;h.result=void 0===g&&h.cjs?h.cjs.exports:g;pa(h)}return h.result},X=0,ja=function(h){try{X++,h()}finally{X--}La()&&J("idle",[])},da=function(){X||ja(function(){for(var h,a,b=0;b<R.length;)h=
oa,a=R[b],ka(a),h!=oa?b=0:b++})};void 0===t("dojo-loader-eval-hint-url")&&t.add("dojo-loader-eval-hint-url",1);var Ea=function(h){h+="";return h+(A?(/\?/.test(h)?"\x26":"?")+A:"")},Ga=function(h){var a=h.plugin;5===a.executed&&!a.load&&na(a);var b=function(a){h.result=a;fa(h);pa(h);da()};a.load?a.load(h.prid,h.req,b):a.loadQ?a.loadQ.push(h):(a.loadQ=[h],R.unshift(a),za(a))},ha=0,qa=0,ra=0,Ra=function(h,a){"function"===typeof f.moduleTextTransform&&(h=f.moduleTextTransform(h,a));t("config-stripStrict")&&
(h=h.replace(/"use strict"/g,""));ra=1;h===ha?ha.call(null):r.eval(h,t("dojo-loader-eval-hint-url")?a.url:a.mid);ra=0},za=function(a){var q=a.mid,g=a.url;if(!a.executed&&!a.injected&&!(N[q]||a.url&&(a.pack&&N[a.url]===a.pack||1==N[a.url])))if(Ja(a),a.plugin)Ga(a);else{var e=function(){Sa(a);if(2!==a.injected){if(t("dojo-enforceDefine")){J("error",c("noDefine",a));return}fa(a);b(a,Fa);r.trace("loader-define-nonmodule",[a.url])}da()};(ha=y[q]||y["url:"+a.url])?(r.trace("loader-inject",["cache",a.mid,
g]),Ra(ha,a),e()):(r.trace("loader-inject",["script",a.mid,g]),qa=a,r.injectUrl(Ea(g),e,a),qa=0)}},sa=function(a,q,g){r.trace("loader-define-module",[a.mid,q]);if(2===a.injected)return J("error",c("multipleDefine",a)),a;b(a,{deps:q,def:g,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var e=0;q[e];e++)q[e]=S(q[e],a);fa(a);!k(g)&&!q.length&&(a.result=g,pa(a));return a},Sa=function(a,b){for(var c=[],q,g;ea.length;)g=ea.shift(),
b&&(g[0]=b.shift()),q=g[0]&&S(g[0])||a,c.push([q,g[1],g[2]]);H(a);s(c,function(a){ba(sa.apply(null,a))})},Ka=m,Ia=m;t.add("ie-event-behavior",u.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var ta=function(a,b,c,q){if(t("ie-event-behavior"))return a.attachEvent(c,q),function(){a.detachEvent(c,q)};a.addEventListener(b,q,!1);return function(){a.removeEventListener(b,q,!1)}},Ta=ta(window,"load","onload",function(){r.pageLoaded=1;"complete"!=
u.readyState&&(u.readyState="complete");Ta()}),Q=u.getElementsByTagName("script");for(d=0;!U;)if(!/^dojo/.test((K=Q[d++])&&K.type))U=K;r.injectUrl=function(a,b,q){q=q.node=u.createElement("script");var g=ta(q,"load","onreadystatechange",function(a){a=a||window.event;var h=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(h.readyState))g(),e(),b&&b()}),e=ta(q,"error","onerror",function(b){g();e();J("error",c("scriptError",[a,b]))});q.type="text/javascript";q.charset="utf-8";q.src=a;
U.parentNode.insertBefore(q,U);return q};r.log=m;r.trace=m;K=function(a,b,q){var e=arguments.length,s=["require","exports","module"],d=[0,a,b];1==e?d=[0,k(a)?s:[],a]:2==e&&g(a)?d=[a,k(b)?s:[],b]:3==e&&(d=[a,b,q]);r.trace("loader-define",d.slice(0,2));if((e=d[0]&&S(d[0]))&&!N[e.mid])ba(sa(e,d[1],d[2]));else if(!t("ie-event-behavior")||ra)ea.push(d);else{e=e||qa;if(!e)for(a in N)if((s=D[a])&&s.node&&"interactive"===s.node.readyState){e=s;break}e?(H(e),ba(sa(e,d[1],d[2]))):J("error",c("ieDefineFailed",
d[0]));da()}};K.amd={vendor:"dojotoolkit.org"};b(b(r,p.loaderPatch),f.loaderPatch);Z("error",function(a){try{if(a instanceof Error)for(var b in a);}catch(q){}});b(r,{uid:C,cache:y,packs:T});v.define||(v.define=K,v.require=r,s(V,function(a){O(a)}),Z=x.deps||f.deps||p.deps,x=x.callback||f.callback||p.callback,r.boot=Z||x?[Z||[],x]:0)})(this.dojoConfig||this.djConfig||this.require||{},{async:1,defaultDuration:1,hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,
dom:1,"host-browser":1},packages:[{location:"../dgrid",main:"OnDemandGrid",name:"dgrid"},{location:"../dijit",name:"dijit"},{location:"../spinner",name:"spinner"},{location:"../xstyle",name:"xstyle"},{location:".",name:"dojo"},{location:"../put-selector",main:"put",name:"put-selector"},{location:"../webview",name:"webview"}],tlmSiblingOfDojo:0});
require({cache:{"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(f,p){var d=document.createElement("div"),l=d.matchesSelector||d.webkitMatchesSelector||d.mozMatchesSelector||d.msMatchesSelector||d.oMatchesSelector,m=d.querySelectorAll,e=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;f.add("dom-matches-selector",!!l);f.add("dom-qsa",!!m);var n=function(e,b){if(a&&-1<e.indexOf(","))return a(e,b);var c=b?b.ownerDocument||b:p.doc||document,d=(m?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:
/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(e);b=b||c;if(d){if(d[2]){var f=p.byId?p.byId(d[2],c):c.getElementById(d[2]);if(!f||d[1]&&d[1]!=f.tagName.toLowerCase())return[];if(b!=c)for(c=f;c!=b;)if(c=c.parentNode,!c)return[];return d[3]?n(d[3],f):[f]}if(d[3]&&b.getElementsByClassName)return b.getElementsByClassName(d[4]);if(d[5])if(f=b.getElementsByTagName(d[5]),d[4]||d[6])e=(d[4]||"")+d[6];else return f}if(m)return 1===b.nodeType&&"object"!==b.nodeName.toLowerCase()?k(b,
e,b.querySelectorAll):b.querySelectorAll(e);f||(f=b.getElementsByTagName("*"));for(var d=[],c=0,r=f.length;c<r;c++){var l=f[c];1==l.nodeType&&g(l,e,b)&&d.push(l)}return d},k=function(a,b,c){var g=a,d=a.getAttribute("id"),k=d||"__dojo__",f=a.parentNode,m=/^\s*[+~]/.test(b);if(m&&!f)return[];d?k=k.replace(/'/g,"\\$\x26"):a.setAttribute("id",k);m&&f&&(a=a.parentNode);b=b.match(e);for(f=0;f<b.length;f++)b[f]="[id\x3d'"+k+"'] "+b[f];b=b.join(",");try{return c.call(a,b)}finally{d||g.removeAttribute("id")}};
if(!f("dom-matches-selector"))var g=function(){function a(b,c,e){var g=c.charAt(0);if('"'==g||"'"==g)c=c.slice(1,-1);c=c.replace(/\\/g,"");var d=k[e||""];return function(a){return(a=a.getAttribute(b))&&d(a,c)}}function b(a){return function(b,c){for(;(b=b.parentNode)!=c;)if(a(b,c))return!0}}function c(a){return function(b,c){b=b.parentNode;return a?b!=c&&a(b,c):b==c}}function e(a,b){return a?function(c,e){return b(c)&&a(c,e)}:b}var g="div"==d.tagName?"toLowerCase":"toUpperCase",f={"":function(a){a=
a[g]();return function(b){return b.tagName==a}},".":function(a){var b=" "+a+" ";return function(c){return-1<c.className.indexOf(a)&&-1<(" "+c.className+" ").indexOf(b)}},"#":function(a){return function(b){return b.id==a}}},k={"^\x3d":function(a,b){return 0==a.indexOf(b)},"*\x3d":function(a,b){return-1<a.indexOf(b)},"$\x3d":function(a,b){return a.substring(a.length-b.length,a.length)==b},"~\x3d":function(a,b){return-1<(" "+a+" ").indexOf(" "+b+" ")},"|\x3d":function(a,b){return 0==(a+"-").indexOf(b+
"-")},"\x3d":function(a,b){return a==b},"":function(a,b){return!0}},m={};return function(g,d,k){var l=m[d];if(!l){if(d.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(g,q,d,k,m,n,t){k?l=e(l,f[d||""](k.replace(/\\/g,""))):q?l=(" "==q?b:c)(l):m&&(l=e(l,a(m,t,n)));return""}))throw Error("Syntax error in query");if(!l)return!0;m[d]=l}return l(g,k)}}();if(!f("dom-qsa"))var a=function(a,b){for(var c=a.match(e),g=
[],d=0;d<c.length;d++){a=new String(c[d].replace(/\s*$/,""));a.indexOf=escape;for(var k=n(a,b),f=0,m=k.length;f<m;f++){var l=k[f];g[l.sourceIndex]=l}}c=[];for(d in g)c.push(g[d]);return c};n.match=l?function(a,b,c){return c&&9!=c.nodeType?k(c,b,function(b){return l.call(a,b)}):l.call(a,b)}:g;return n})},"dojo/_base/window":function(){define(["./kernel","./lang","../sniff"],function(f,p,d){var l={global:f.global,doc:this.document||null,body:function(d){d=d||f.doc;return d.body||d.getElementsByTagName("body")[0]},
setContext:function(d,e){f.global=l.global=d;f.doc=l.doc=e},withGlobal:function(d,e,n,k){var g=f.global;try{return f.global=l.global=d,l.withDoc.call(null,d.document,e,n,k)}finally{f.global=l.global=g}},withDoc:function(m,e,n,k){var g=l.doc,a=d("quirks"),s=d("ie"),b,c,B;try{f.doc=l.doc=m;f.isQuirks=d.add("quirks","BackCompat"==f.doc.compatMode,!0,!0);if(d("ie")&&(B=m.parentWindow)&&B.navigator)b=parseFloat(B.navigator.appVersion.split("MSIE ")[1])||void 0,(c=m.documentMode)&&(5!=c&&Math.floor(b)!=
c)&&(b=c),f.isIE=d.add("ie",b,!0,!0);n&&"string"==typeof e&&(e=n[e]);return e.apply(n,k||[])}finally{f.doc=l.doc=g,f.isQuirks=d.add("quirks",a,!0,!0),f.isIE=d.add("ie",s,!0,!0)}}};p.mixin(f,l);return l})},"dojo/_base/lang":function(){define(["./kernel","../has","../sniff"],function(f,p){p.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var d=p("bug-for-in-skips-shadowed")?"hasOwnProperty valueOf isPrototypeOf propertyIsEnumerable toLocaleString toString constructor".split(" "):
[],l=d.length,m=function(a,d,b){var c,g=0,e=f.global;if(!b)if(a.length){c=a[g++];try{b=f.scopeMap[c]&&f.scopeMap[c][1]}catch(k){}b=b||(c in e?e[c]:d?e[c]={}:void 0)}else return e;for(;b&&(c=a[g++]);)b=c in b?b[c]:d?b[c]={}:void 0;return b},e=Object.prototype.toString,n=function(a,d,b){return(b||[]).concat(Array.prototype.slice.call(a,d||0))},k=/\{([^\}]+)\}/g,g={_extraNames:d,_mixin:function(a,e,b){var c,g,k,f={};for(c in e)if(g=e[c],!(c in a)||a[c]!==g&&(!(c in f)||f[c]!==g))a[c]=b?b(g):g;if(p("bug-for-in-skips-shadowed")&&
e)for(k=0;k<l;++k)if(c=d[k],g=e[c],!(c in a)||a[c]!==g&&(!(c in f)||f[c]!==g))a[c]=b?b(g):g;return a},mixin:function(a,d){a||(a={});for(var b=1,c=arguments.length;b<c;b++)g._mixin(a,arguments[b]);return a},setObject:function(a,d,b){var c=a.split(".");a=c.pop();return(b=m(c,!0,b))&&a?b[a]=d:void 0},getObject:function(a,d,b){return m(a.split("."),d,b)},exists:function(a,d){return void 0!==g.getObject(a,!1,d)},isString:function(a){return"string"==typeof a||a instanceof String},isArray:function(a){return a&&
(a instanceof Array||"array"==typeof a)},isFunction:function(a){return"[object Function]"===e.call(a)},isObject:function(a){return void 0!==a&&(null===a||"object"==typeof a||g.isArray(a)||g.isFunction(a))},isArrayLike:function(a){return a&&void 0!==a&&!g.isString(a)&&!g.isFunction(a)&&!(a.tagName&&"form"==a.tagName.toLowerCase())&&(g.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!g.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},extend:function(a,d){for(var b=1,c=arguments.length;b<
c;b++)g._mixin(a.prototype,arguments[b]);return a},_hitchArgs:function(a,d){var b=g._toArray(arguments,2),c=g.isString(d);return function(){var e=g._toArray(arguments),k=c?(a||f.global)[d]:d;return k&&k.apply(a||this,b.concat(e))}},hitch:function(a,d){if(2<arguments.length)return g._hitchArgs.apply(f,arguments);d||(d=a,a=null);if(g.isString(d)){a=a||f.global;if(!a[d])throw['lang.hitch: scope["',d,'"] is null (scope\x3d"',a,'")'].join("");return function(){return a[d].apply(a,arguments||[])}}return!a?
d:function(){return d.apply(a,arguments||[])}},delegate:function(){function a(){}return function(d,b){a.prototype=d;var c=new a;a.prototype=null;b&&g._mixin(c,b);return c}}(),_toArray:p("ie")?function(){function a(a,b,c){c=c||[];for(b=b||0;b<a.length;b++)c.push(a[b]);return c}return function(d){return(d.item?a:n).apply(this,arguments)}}():n,partial:function(a){return g.hitch.apply(f,[null].concat(g._toArray(arguments)))},clone:function(a){if(!a||"object"!=typeof a||g.isFunction(a))return a;if(a.nodeType&&
"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var d,b,c;if(g.isArray(a)){d=[];b=0;for(c=a.length;b<c;++b)b in a&&d.push(g.clone(a[b]))}else d=a.constructor?new a.constructor:{};return g._mixin(d,a,g.clone)},trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,d,b){return a.replace(b||k,g.isFunction(d)?d:function(a,b){return g.getObject(b,
!1,d)})}};g.mixin(f,g);return g})},"dojo/has":function(){define(["require","module"],function(f,p){var d=f.has||function(){};d.add("dom-addeventlistener",!!document.addEventListener);d.add("touch","ontouchstart"in document||0<window.navigator.msMaxTouchPoints);d.add("device-width",screen.availWidth||innerWidth);var l=document.createElement("form");d.add("dom-attributes-explicit",0==l.attributes.length);d.add("dom-attributes-specified-flag",0<l.attributes.length&&40>l.attributes.length);d.clearElement=
function(d){d.innerHTML="";return d};d.normalize=function(f,e){var l=f.match(/[\?:]|[^:\?]*/g),k=0,g=function(a){var e=l[k++];if(":"==e)return 0;if("?"==l[k++]){if(!a&&d(e))return g();g(!0);return g(a)}return e||0};return(f=g())&&e(f)};d.load=function(d,e,f){d?e([d],f):f()};return d})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(f,p,d,l){var m;f={};var e={},n={config:p,global:this,dijit:f,dojox:e};f={dojo:["dojo",n],dijit:["dijit",f],dojox:["dojox",e]};
l=d.map&&d.map[l.id.match(/[^\/]+/)[0]];for(m in l)f[m]?f[m][0]=l[m]:f[m]=[l[m],{}];for(m in f)l=f[m],l[1]._scopeName=l[0],p.noGlobals||(this[l[0]]=l[1]);n.scopeMap=f;n.baseUrl=n.config.baseUrl=d.baseUrl;n.isAsync=d.async;n.locale=p.locale;p="$Rev: fd52c96 $".match(/[0-9a-f]{7,}/);n.version={major:1,minor:9,patch:3,flag:"",revision:p?p[0]:NaN,toString:function(){var d=n.version;return d.major+"."+d.minor+"."+d.patch+d.flag+" ("+d.revision+")"}};Function("d","d.eval \x3d function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(n);
n.exit=function(){};"undefined"!=typeof console||(console={});d="assert count debug dir dirxml error group groupEnd info profile profileEnd time timeEnd trace warn log".split(" ");var k;for(p=0;k=d[p++];)console[k]||function(){var d=k+"";console[d]="log"in console?function(){var a=Array.apply({},arguments);a.unshift(d+":");console.log(a.join(" "))}:function(){};console[d]._fake=!0}();n.deprecated=n.experimental=function(){};n._hasResource={};return n})},"dojo/promise/Promise":function(){define(["../_base/lang"],
function(f){function p(){throw new TypeError("abstract");}return f.extend(function(){},{then:function(d,f,m){p()},cancel:function(d,f){p()},isResolved:function(){p()},isRejected:function(){p()},isFulfilled:function(){p()},isCanceled:function(){p()},always:function(d){return this.then(d,d)},otherwise:function(d){return this.then(null,d)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},"dojo/query":function(){define("./_base/kernel ./has ./dom ./on ./_base/array ./_base/lang ./selector/_loader ./selector/_loader!default".split(" "),
function(f,p,d,l,m,e,n,k){function g(a,b){var c=function(c,q){if("string"==typeof q&&(q=d.byId(q),!q))return new b([]);var e="string"==typeof c?a(c,q):c?c.end&&c.on?c:[c]:[];return e.end&&e.on?e:new b(e)};c.matches=a.match||function(a,b,d){return 0<c.filter([a],b,d).length};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return-1<m.indexOf(a,b)})};if("function"!=typeof a){var e=a.search;a=function(a,b){return e(b||document,a)}}return c}p.add("array-extensible",function(){return 1==
e.delegate([],{length:1}).length&&!p("bug-for-in-skips-shadowed")});var a=Array.prototype,s=a.slice,b=a.concat,c=m.forEach,B=function(a,b,c){b=[0].concat(s.call(b,0));c=c||f.global;return function(d){b[0]=d;return a.apply(c,b)}},C=function(a){var b=this instanceof r&&p("array-extensible");"number"==typeof a&&(a=Array(a));var c=a&&"length"in a?a:arguments;if(b||!c.sort){for(var d=b?this:[],g=d.length=c.length,q=0;q<g;q++)d[q]=c[q];if(b)return d;c=d}e._mixin(c,v);c._NodeListCtor=function(a){return r(a)};
return c},r=C,v=r.prototype=p("array-extensible")?[]:{};r._wrap=v._wrap=function(a,b,c){a=new (c||this._NodeListCtor||r)(a);return b?a._stash(b):a};r._adaptAsMap=function(a,b){return function(){return this.map(B(a,arguments,b))}};r._adaptAsForEach=function(a,b){return function(){this.forEach(B(a,arguments,b));return this}};r._adaptAsFilter=function(a,b){return function(){return this.filter(B(a,arguments,b))}};r._adaptWithCondition=function(a,b,c){return function(){var d=arguments,e=B(a,d,c);if(b.call(c||
f.global,d))return this.map(e);this.forEach(e);return this}};c(["slice","splice"],function(b){var c=a[b];v[b]=function(){return this._wrap(c.apply(this,arguments),"slice"==b?this:null)}});c(["indexOf","lastIndexOf","every","some"],function(a){var b=m[a];v[a]=function(){return b.apply(f,[this].concat(s.call(arguments,0)))}});e.extend(C,{constructor:r,_NodeListCtor:r,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,b){var c=this.map(function(c){return l(c,
a,b)});c.remove=function(){for(var a=0;a<c.length;a++)c[a].remove()};return c},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(a){var c=s.call(this,0),d=m.map(arguments,function(a){return s.call(a,0)});return this._wrap(b.apply(c,d),this)},map:function(a,b){return this._wrap(m.map(this,a,b),this)},forEach:function(a,b){c(this,a,b);return this},filter:function(a){var b=arguments,c=this,d=0;if("string"==typeof a){c=u._filterResult(this,b[0]);if(1==b.length)return c._stash(this);
d=1}return this._wrap(m.filter(c,b[d],b[d+1]),this)},instantiate:function(a,b){var c=e.isFunction(a)?a:e.getObject(a);b=b||{};return this.forEach(function(a){new c(b,a)})},at:function(){var a=new this._NodeListCtor(0);c(arguments,function(b){0>b&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});var u=g(k,C);f.query=g(k,function(a){return C(a)});u.load=function(a,b,c){n.load(a,b,function(a){c(g(a,C))})};f._filterQueryResult=u._filterResult=function(a,b,c){return new C(u.filter(a,
b,c))};f.NodeList=u.NodeList=C;return u})},"dojo/selector/_loader":function(){define(["../has","require"],function(f,p){var d=document.createElement("div");f.add("dom-qsa2.1",!!d.querySelectorAll);f.add("dom-qsa3",function(){try{return d.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e",1==d.querySelectorAll(".TEST:empty").length}catch(f){}});var l;return{load:function(d,e,n,k){k=p;d="default"==d?f("config-selectorEngine")||"css3":d;d="css2"==d||"lite"==d?"./lite":"css2.1"==d?f("dom-qsa2.1")?"./lite":
"./acme":"css3"==d?f("dom-qsa3")?"./lite":"./acme":"acme"==d?"./acme":(k=e)&&d;if("?"==d.charAt(d.length-1)){d=d.substring(0,d.length-1);var g=!0}if(g&&(f("dom-compliant-qsa")||l))return n(l);k([d],function(a){"./lite"!=d&&(l=a);n(a)})}}})},"dojo/parser":function(){define("require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),function(f,p,d,l,m,e,n,k,g,a,s,b,c,B,C,r){function v(a){return eval("("+
a+")")}function u(a){var b=a._nameCaseMap,c=a.prototype;if(!b||b._extendCnt<t){var b=a._nameCaseMap={},d;for(d in c)"_"!==d.charAt(0)&&(b[d.toLowerCase()]=d);b._extendCnt=t}return b}function L(a,b){var c=a.join();if(!w[c]){for(var e=[],g=0,k=a.length;g<k;g++){var l=a[g];e[e.length]=w[l]=w[l]||d.getObject(l)||~l.indexOf("/")&&(b?b(l):f(l))}g=e.shift();w[c]=e.length?g.createSubclass?g.createSubclass(e):g.extend.apply(g,e):g}return w[c]}new Date("X");var t=0;g.after(d,"extend",function(){t++},!0);var w=
{},x={_clearCache:function(){t++;w={}},_functionFromScript:function(a,b){var c="",d="",e=a.getAttribute(b+"args")||a.getAttribute("args"),g=a.getAttribute("with"),e=(e||"").split(/\s*,\s*/);g&&g.length&&l.forEach(g.split(/\s*,\s*/),function(a){c+="with("+a+"){";d+="}"});return new Function(e,c+a.innerHTML+d)},instantiate:function(a,b,c){b=b||{};c=c||{};var d=(c.scope||p._scopeName)+"Type",e="data-"+(c.scope||p._scopeName)+"-",g=e+"type",f=e+"mixins",k=[];l.forEach(a,function(a){var c=d in b?b[d]:
a.getAttribute(g)||a.getAttribute(d);if(c){var e=a.getAttribute(f),c=e?[c].concat(e.split(/\s*,\s*/)):[c];k.push({node:a,types:c})}});return this._instantiate(k,b,c)},_instantiate:function(b,c,d,e){function g(a){!c._started&&!d.noStart&&l.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a}b=l.map(b,function(a){var b=a.ctor||L(a.types,d.contextRequire);if(!b)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(b,a.node,c,
d,a.scripts,a.inherited)},this);return e?a(b).then(g):g(b)},construct:function(a,b,e,f,r,m){function n(a){w&&d.setObject(w,a);for(y=0;y<I.length;y++)g[I[y].advice||"after"](a,I[y].method,d.hitch(a,I[y].func),!0);for(y=0;y<V.length;y++)V[y].call(a);for(y=0;y<O.length;y++)a.watch(O[y].prop,O[y].func);for(y=0;y<Q.length;y++)C(a,Q[y].event,Q[y].func);return a}var t=a&&a.prototype;f=f||{};var E={};f.defaults&&d.mixin(E,f.defaults);m&&d.mixin(E,m);var F;c("dom-attributes-explicit")?F=b.attributes:c("dom-attributes-specified-flag")?
F=l.filter(b.attributes,function(a){return a.specified}):(m=(/^input$|^img$/i.test(b.nodeName)?b:b.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),F=l.map(m.split(/\s+/),function(a){var c=a.toLowerCase();return{name:a,value:"LI"==b.nodeName&&"value"==a||"enctype"==c?b.getAttribute(c):b.getAttributeNode(c).value}}));var D=f.scope||p._scopeName;m="data-"+D+"-";var A={};"dojo"!==D&&(A[m+"props"]="data-dojo-props",A[m+"type"]=
"data-dojo-type",A[m+"mixins"]="data-dojo-mixins",A[D+"type"]="dojoType",A[m+"id"]="data-dojo-id");for(var y=0,z,D=[],w,H;z=F[y++];){var G=z.name,x=G.toLowerCase();z=z.value;switch(A[x]||x){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":H=z;break;case "data-dojo-id":case "jsid":w=z;break;case "data-dojo-attach-point":case "dojoattachpoint":E.dojoAttachPoint=z;break;case "data-dojo-attach-event":case "dojoattachevent":E.dojoAttachEvent=z;break;case "class":E["class"]=
b.className;break;case "style":E.style=b.style&&b.style.cssText;break;default:if(G in t||(G=u(a)[x]||G),G in t)switch(typeof t[G]){case "string":E[G]=z;break;case "number":E[G]=z.length?Number(z):NaN;break;case "boolean":E[G]="false"!=z.toLowerCase();break;case "function":""===z||-1!=z.search(/[^\w\.]+/i)?E[G]=new Function(z):E[G]=d.getObject(z,!1)||new Function(z);D.push(G);break;default:x=t[G],E[G]=x&&"length"in x?z?z.split(/\s*,\s*/):[]:x instanceof Date?""==z?new Date(""):"now"==z?new Date:s.fromISOString(z):
x instanceof k?p.baseUrl+z:v(z)}else E[G]=z}}for(F=0;F<D.length;F++)A=D[F].toLowerCase(),b.removeAttribute(A),b[A]=null;if(H)try{H=v.call(f.propsThis,"{"+H+"}"),d.mixin(E,H)}catch(L){throw Error(L.toString()+" in data-dojo-props\x3d'"+H+"'");}d.mixin(E,e);r||(r=a&&(a._noScript||t._noScript)?[]:B("\x3e script[type^\x3d'dojo/']",b));var I=[],V=[],O=[],Q=[];if(r)for(y=0;y<r.length;y++)A=r[y],b.removeChild(A),e=A.getAttribute(m+"event")||A.getAttribute("event"),f=A.getAttribute(m+"prop"),H=A.getAttribute(m+
"method"),D=A.getAttribute(m+"advice"),F=A.getAttribute("type"),A=this._functionFromScript(A,m),e?"dojo/connect"==F?I.push({method:e,func:A}):"dojo/on"==F?Q.push({event:e,func:A}):E[e]=A:"dojo/aspect"==F?I.push({method:H,advice:D,func:A}):"dojo/watch"==F?O.push({prop:f,func:A}):V.push(A);a=(r=a.markupFactory||t.markupFactory)?r(E,b,a):new a(E,b);return a.then?a.then(n):n(a)},scan:function(a,c){function d(a){if(!a.inherited){a.inherited={};var b=a.node,c=d(a.parent),b={dir:b.getAttribute("dir")||c.dir,
lang:b.getAttribute("lang")||c.lang,textDir:b.getAttribute(B)||c.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var e=[],g=[],k={},m=(c.scope||p._scopeName)+"Type",r="data-"+(c.scope||p._scopeName)+"-",n=r+"type",B=r+"textdir",r=r+"mixins",s=a.firstChild,v=c.inherited;if(!v){var C=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&C(a.parentNode,b)},v={dir:C(a,"dir"),lang:C(a,"lang"),textDir:C(a,B)},t;for(t in v)v[t]||delete v[t]}for(var v={inherited:v},u,
w;;)if(s)if(1!=s.nodeType)s=s.nextSibling;else if(u&&"script"==s.nodeName.toLowerCase())(x=s.getAttribute("type"))&&/^dojo\/\w/i.test(x)&&u.push(s),s=s.nextSibling;else if(w)s=s.nextSibling;else{var x=s.getAttribute(n)||s.getAttribute(m);t=s.firstChild;if(!x&&(!t||3==t.nodeType&&!t.nextSibling))s=s.nextSibling;else{w=null;if(x){var P=s.getAttribute(r);u=P?[x].concat(P.split(/\s*,\s*/)):[x];try{w=L(u,c.contextRequire)}catch(ya){}w||l.forEach(u,function(a){~a.indexOf("/")&&!k[a]&&(k[a]=!0,g[g.length]=
a)});P=w&&!w.prototype._noScript?[]:null;v={types:u,ctor:w,parent:v,node:s,scripts:P};v.inherited=d(v);e.push(v)}else v={node:s,scripts:u,parent:v};u=P;w=s.stopParser||w&&w.prototype.stopParser&&!c.template;s=t}}else{if(!v||!v.node)break;s=v.node.nextSibling;w=!1;v=v.parent;u=v.scripts}var I=new b;g.length?(c.contextRequire||f)(g,function(){I.resolve(l.filter(e,function(a){if(!a.ctor)try{a.ctor=L(a.types,c.contextRequire)}catch(b){}for(var d=a.parent;d&&!d.types;)d=d.parent;var e=a.ctor&&a.ctor.prototype;
a.instantiateChildren=!(e&&e.stopParser&&!c.template);a.instantiate=!d||d.instantiate&&d.instantiateChildren;return a.instantiate}))}):I.resolve(e);return I.promise},_require:function(a,c){var e=v("{"+a.innerHTML+"}"),g=[],k=[],l=new b,m=c&&c.contextRequire||f,r;for(r in e)g.push(r),k.push(e[r]);m(k,function(){for(var a=0;a<g.length;a++)d.setObject(g[a],arguments[a]);l.resolve(arguments)});return l.promise},_scanAmd:function(a,c){var d=new b,e=d.promise;d.resolve(!0);var g=this;B("script[type\x3d'dojo/require']",
a).forEach(function(a){e=e.then(function(){return g._require(a,c)});a.parentNode.removeChild(a)});return e},parse:function(a,b){var c;!b&&a&&a.rootNode?(b=a,c=b.rootNode):a&&d.isObject(a)&&!("nodeType"in a)?b=a:c=a;c=c?e.byId(c):n.body();b=b||{};var g=b.template?{template:!0}:{},f=[],k=this,l=this._scanAmd(c,b).then(function(){return k.scan(c,b)}).then(function(a){return k._instantiate(a,g,b,!0)}).then(function(a){return f=f.concat(a)}).otherwise(function(a){throw a;});d.mixin(f,l);return f}};p.parser=
x;m.parseOnLoad&&r(100,x,"parse");return x})},"dojo/errors/create":function(){define(["../_base/lang"],function(f){return function(p,d,l,m){l=l||Error;var e=function(f){if(l===Error){Error.captureStackTrace&&Error.captureStackTrace(this,e);var k=Error.call(this,f),g;for(g in k)k.hasOwnProperty(g)&&(this[g]=k[g]);this.message=f;this.stack=k.stack}else l.apply(this,arguments);d&&d.apply(this,arguments)};e.prototype=f.delegate(l.prototype,m);e.prototype.name=p;return e.prototype.constructor=e}})},"dojo/_base/array":function(){define(["./kernel",
"../has","./lang"],function(f,p,d){function l(a){return n[a]=new Function("item","index","array",a)}function m(a){var d=!a;return function(b,c,e){var g=0,f=b&&b.length||0,k;f&&"string"==typeof b&&(b=b.split(""));"string"==typeof c&&(c=n[c]||l(c));if(e)for(;g<f;++g){if(k=!c.call(e,b[g],g,b),a^k)return!k}else for(;g<f;++g)if(k=!c(b[g],g,b),a^k)return!k;return d}}function e(a){var d=1,b=0,c=0;a||(d=b=c=-1);return function(e,f,l,m){if(m&&0<d)return g.lastIndexOf(e,f,l);m=e&&e.length||0;var n=a?m+c:b;
l===k?l=a?b:m+c:0>l?(l=m+l,0>l&&(l=b)):l=l>=m?m+c:l;for(m&&"string"==typeof e&&(e=e.split(""));l!=n;l+=d)if(e[l]==f)return l;return-1}}var n={},k,g={every:m(!1),some:m(!0),indexOf:e(!0),lastIndexOf:e(!1),forEach:function(a,d,b){var c=0,e=a&&a.length||0;e&&"string"==typeof a&&(a=a.split(""));"string"==typeof d&&(d=n[d]||l(d));if(b)for(;c<e;++c)d.call(b,a[c],c,a);else for(;c<e;++c)d(a[c],c,a)},map:function(a,d,b,c){var e=0,g=a&&a.length||0;c=new (c||Array)(g);g&&"string"==typeof a&&(a=a.split(""));
"string"==typeof d&&(d=n[d]||l(d));if(b)for(;e<g;++e)c[e]=d.call(b,a[e],e,a);else for(;e<g;++e)c[e]=d(a[e],e,a);return c},filter:function(a,d,b){var c=0,e=a&&a.length||0,g=[],f;e&&"string"==typeof a&&(a=a.split(""));"string"==typeof d&&(d=n[d]||l(d));if(b)for(;c<e;++c)f=a[c],d.call(b,f,c,a)&&g.push(f);else for(;c<e;++c)f=a[c],d(f,c,a)&&g.push(f);return g},clearCache:function(){n={}}};d.mixin(f,g);return g})},"dojo/dom":function(){define(["./sniff","./_base/window"],function(f,p){if(7>=f("ie"))try{document.execCommand("BackgroundImageCache",
!1,!0)}catch(d){}var l={};f("ie")?l.byId=function(d,f){if("string"!=typeof d)return d;var k=f||p.doc,g=d&&k.getElementById(d);if(g&&(g.attributes.id.value==d||g.id==d))return g;k=k.all[d];if(!k||k.nodeName)k=[k];for(var a=0;g=k[a++];)if(g.attributes&&g.attributes.id&&g.attributes.id.value==d||g.id==d)return g}:l.byId=function(d,f){return("string"==typeof d?(f||p.doc).getElementById(d):d)||null};l.isDescendant=function(d,f){try{d=l.byId(d);for(f=l.byId(f);d;){if(d==f)return!0;d=d.parentNode}}catch(k){}return!1};
f.add("css-user-select",function(d,f,k){if(!k)return!1;d=k.style;f=["Khtml","O","ms","Moz","Webkit"];k=f.length;var g="userSelect";do if("undefined"!==typeof d[g])return g;while(k--&&(g=f[k]+"UserSelect"));return!1});var m=f("css-user-select");l.setSelectable=m?function(d,f){l.byId(d).style[m]=f?"":"none"}:function(d,f){d=l.byId(d);var k=d.getElementsByTagName("*"),g=k.length;if(f)for(d.removeAttribute("unselectable");g--;)k[g].removeAttribute("unselectable");else for(d.setAttribute("unselectable",
"on");g--;)k[g].setAttribute("unselectable","on")};return l})},"dojo/sniff":function(){define(["./has"],function(f){var p=navigator,d=p.userAgent,p=p.appVersion,l=parseFloat(p);f.add("air",0<=d.indexOf("AdobeAIR"));f.add("msapp",parseFloat(d.split("MSAppHost/")[1])||void 0);f.add("khtml",0<=p.indexOf("Konqueror")?l:void 0);f.add("webkit",parseFloat(d.split("WebKit/")[1])||void 0);f.add("chrome",parseFloat(d.split("Chrome/")[1])||void 0);f.add("safari",0<=p.indexOf("Safari")&&!f("chrome")?parseFloat(p.split("Version/")[1]):
void 0);f.add("mac",0<=p.indexOf("Macintosh"));f.add("quirks","BackCompat"==document.compatMode);if(d.match(/(iPhone|iPod|iPad)/)){var m=RegExp.$1.replace(/P/,"p"),e=d.match(/OS ([\d_]+)/)?RegExp.$1:"1",e=parseFloat(e.replace(/_/,".").replace(/_/g,""));f.add(m,e);f.add("ios",e)}f.add("android",parseFloat(d.split("Android ")[1])||void 0);f.add("bb",(0<=d.indexOf("BlackBerry")||0<=d.indexOf("BB10"))&&parseFloat(d.split("Version/")[1])||void 0);f.add("trident",parseFloat(p.split("Trident/")[1])||void 0);
f.add("svg","undefined"!==typeof SVGAngle);f("webkit")||(0<=d.indexOf("Opera")&&f.add("opera",9.8<=l?parseFloat(d.split("Version/")[1])||l:l),0<=d.indexOf("Gecko")&&(!f("khtml")&&!f("webkit")&&!f("trident"))&&f.add("mozilla",l),f("mozilla")&&f.add("ff",parseFloat(d.split("Firefox/")[1]||d.split("Minefield/")[1])||void 0),document.all&&!f("opera")&&(d=parseFloat(p.split("MSIE ")[1])||void 0,(p=document.documentMode)&&(5!=p&&Math.floor(d)!=p)&&(d=p),f.add("ie",d)),f.add("wii","undefined"!=typeof opera&&
opera.wiiremote));return f})},"dojo/_base/config":function(){define(["../has","require"],function(f,p){var d={},l=p.rawConfig,m;for(m in l)d[m]=l[m];!d.locale&&"undefined"!=typeof navigator&&(d.locale=(navigator.language||navigator.userLanguage).toLowerCase());return d})},"dojo/errors/CancelError":function(){define(["./create"],function(f){return f("CancelError",null,null,{dojoType:"cancel"})})},"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise","require"],
function(f,p,d,l,m){var e=Object.freeze||function(){},n=function(a,d,e,g,f){for(f=0;f<a.length;f++)k(a[f],d,e,g)},k=function(b,d,e,f){f=b[d];var k=b.deferred;if(f)try{var l=f(e);0===d?"undefined"!==typeof l&&a(k,d,l):l&&"function"===typeof l.then?(b.cancel=l.cancel,l.then(g(k,1),g(k,2),g(k,0))):a(k,1,l)}catch(m){a(k,2,m)}else a(k,d,e)},g=function(b,d){return function(e){a(b,d,e)}},a=function(a,d,e){if(!a.isCanceled())switch(d){case 0:a.progress(e);break;case 1:a.resolve(e);break;case 2:a.reject(e)}},
s=function(a){var c=this.promise=new l,g=this,f,m,p=!1,u=[];this.isResolved=c.isResolved=function(){return 1===f};this.isRejected=c.isRejected=function(){return 2===f};this.isFulfilled=c.isFulfilled=function(){return!!f};this.isCanceled=c.isCanceled=function(){return p};this.progress=function(a,b){if(f){if(!0===b)throw Error("This deferred has already been fulfilled.");return c}n(u,0,a,null,g);return c};this.resolve=function(a,b){if(f){if(!0===b)throw Error("This deferred has already been fulfilled.");
return c}n(u,f=1,m=a,null,g);u=null;return c};var L=this.reject=function(a,b){if(f){if(!0===b)throw Error("This deferred has already been fulfilled.");return c}n(u,f=2,m=a,void 0,g);u=null;return c};this.then=c.then=function(a,b,d){var e=[d,a,b];e.cancel=c.cancel;e.deferred=new s(function(a){return e.cancel&&e.cancel(a)});f&&!u?k(e,f,m,void 0):u.push(e);return e.deferred.promise};this.cancel=c.cancel=function(c,e){if(f){if(!0===e)throw Error("This deferred has already been fulfilled.");}else{if(a){var g=
a(c);c="undefined"===typeof g?c:g}p=!0;if(f){if(2===f&&m===c)return c}else return"undefined"===typeof c&&(c=new d),L(c),c}};e(c)};s.prototype.toString=function(){return"[object Deferred]"};m&&m(s);return s})},"dojo/_base/url":function(){define(["./kernel"],function(f){var p=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,d=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,l=function(){for(var f=arguments,e=[f[0]],n=1;n<f.length;n++)if(f[n]){var k=new l(f[n]+""),e=new l(e[0]+
"");if(""==k.path&&!k.scheme&&!k.authority&&!k.query)null!=k.fragment&&(e.fragment=k.fragment),k=e;else if(!k.scheme&&(k.scheme=e.scheme,!k.authority&&(k.authority=e.authority,"/"!=k.path.charAt(0)))){for(var e=(e.path.substring(0,e.path.lastIndexOf("/")+1)+k.path).split("/"),g=0;g<e.length;g++)"."==e[g]?g==e.length-1?e[g]="":(e.splice(g,1),g--):0<g&&(!(1==g&&""==e[0])&&".."==e[g]&&".."!=e[g-1])&&(g==e.length-1?(e.splice(g,1),e[g-1]=""):(e.splice(g-1,2),g-=2));k.path=e.join("/")}e=[];k.scheme&&e.push(k.scheme,
":");k.authority&&e.push("//",k.authority);e.push(k.path);k.query&&e.push("?",k.query);k.fragment&&e.push("#",k.fragment)}this.uri=e.join("");f=this.uri.match(p);this.scheme=f[2]||(f[1]?"":null);this.authority=f[4]||(f[3]?"":null);this.path=f[5];this.query=f[7]||(f[6]?"":null);this.fragment=f[9]||(f[8]?"":null);null!=this.authority&&(f=this.authority.match(d),this.user=f[3]||null,this.password=f[4]||null,this.host=f[6]||f[7],this.port=f[9]||null)};l.prototype.toString=function(){return this.uri};
return f._Url=l})},"dojo/aspect":function(){define([],function(){function f(d,e,a,f){var b=d[e],c="around"==e,m;if(c){var n=a(function(){return b.advice(this,arguments)});m={remove:function(){n&&(n=d=a=null)},advice:function(a,d){return n?n.apply(a,d):b.advice(a,d)}}}else m={remove:function(){if(m.advice){var b=m.previous,c=m.next;!c&&!b?delete d[e]:(b?b.next=c:d[e]=c,c&&(c.previous=b));d=a=m.advice=null}},id:l++,advice:a,receiveArguments:f};if(b&&!c)if("after"==e){for(;b.next&&(b=b.next););b.next=
m;m.previous=b}else"before"==e&&(d[e]=m,m.next=b,b.previous=m);else d[e]=m;return m}function p(e){return function(g,a,m,b){var c=g[a],n;if(!c||c.target!=g)g[a]=n=function(){for(var a=l,b=arguments,c=n.before;c;)b=c.advice.apply(this,b)||b,c=c.next;if(n.around)var e=n.around.advice(this,b);for(c=n.after;c&&c.id<a;){if(c.receiveArguments)var f=c.advice.apply(this,b),e=f===d?e:f;else e=c.advice.call(this,e,b);c=c.next}return e},c&&(n.around={advice:function(a,b){return c.apply(a,b)}}),n.target=g;g=f(n||
c,e,m,b);m=null;return g}}var d,l=0,m=p("after"),e=p("before"),n=p("around");return{before:e,around:n,after:m}})},"dojo/when":function(){define(["./Deferred","./promise/Promise"],function(f,p){return function(d,l,m,e){var n=d&&"function"===typeof d.then,k=n&&d instanceof p;if(n)k||(n=new f(d.cancel),d.then(n.resolve,n.reject,n.progress),d=n.promise);else return 1<arguments.length?l?l(d):d:(new f).resolve(d);return l||m||e?d.then(l,m,e):d}})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],
function(f,p){var d={};f.setObject("dojo.date.stamp",d);d.fromISOString=function(f,m){d._isoRegExp||(d._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var e=d._isoRegExp.exec(f),n=null;if(e){e.shift();e[1]&&e[1]--;e[6]&&(e[6]*=1E3);m&&(m=new Date(m),p.forEach(p.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return m["get"+a]()}),function(a,d){e[d]=e[d]||a}));n=new Date(e[0]||1970,e[1]||
0,e[2]||1,e[3]||0,e[4]||0,e[5]||0,e[6]||0);100>e[0]&&n.setFullYear(e[0]||1970);var k=0,g=e[7]&&e[7].charAt(0);"Z"!=g&&(k=60*(e[8]||0)+(Number(e[9])||0),"-"!=g&&(k*=-1));g&&(k-=n.getTimezoneOffset());k&&n.setTime(n.getTime()+6E4*k)}return n};d.toISOString=function(d,f){var e=function(a){return 10>a?"0"+a:a};f=f||{};var n=[],k=f.zulu?"getUTC":"get",g="";"time"!=f.selector&&(g=d[k+"FullYear"](),g=["0000".substr((g+"").length)+g,e(d[k+"Month"]()+1),e(d[k+"Date"]())].join("-"));n.push(g);if("date"!=f.selector){g=
[e(d[k+"Hours"]()),e(d[k+"Minutes"]()),e(d[k+"Seconds"]())].join(":");k=d[k+"Milliseconds"]();f.milliseconds&&(g+="."+(100>k?"0":"")+e(k));if(f.zulu)g+="Z";else if("time"!=f.selector)var k=d.getTimezoneOffset(),a=Math.abs(k),g=g+((0<k?"-":"+")+e(Math.floor(a/60))+":"+e(a%60));n.push(g)}return n.join("T")};return d})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(f,p,d){function l(a,c,e,f,l){if(f=c.match(/(.*):(.*)/))return c=f[2],f=f[1],k.selector(f,
c).call(l,a,e);d("touch")&&(g.test(c)&&(e=Y(e)),!d("event-orientationchange")&&"orientationchange"==c&&(c="resize",a=window,e=Y(e)));B&&(e=B(e));if(a.addEventListener){var m=c in b,n=m?b[c]:c;a.addEventListener(n,e,m);return{remove:function(){a.removeEventListener(n,e,m)}}}if(u&&a.attachEvent)return u(a,"on"+c,e);throw Error("Target must be an event emitter");}function m(){this.cancelable=!1;this.defaultPrevented=!0}function e(){this.bubbles=!1}var n=window.ScriptEngineMajorVersion;d.add("jscript",
n&&n()+ScriptEngineMinorVersion()/10);d.add("event-orientationchange",d("touch")&&!d("android"));d.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);d.add("event-focusin",function(a,b,d){return"onfocusin"in d});var k=function(a,b,d,c){return"function"==typeof a.on&&"function"!=typeof b&&!a.nodeType?a.on(b,d):k.parse(a,b,d,l,c,this)};k.pausable=function(a,b,d,c){var e;a=k(a,b,function(){if(!e)return d.apply(this,arguments)},
c);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};k.once=function(a,b,d,c){var e=k(a,b,function(){e.remove();return d.apply(this,arguments)});return e};k.parse=function(a,b,d,c,e,f){if(b.call)return b.call(f,a,d);if(-1<b.indexOf(",")){b=b.split(/\s*,\s*/);for(var g=[],k=0,l;l=b[k++];)g.push(c(a,l,d,e,f));g.remove=function(){for(var a=0;a<g.length;a++)g[a].remove()};return g}return c(a,b,d,e,f)};var g=/^touch/;k.selector=function(a,b,d){return function(c,e){function f(b){for(g=g&&g.matches?
g:p.query;!g.matches(b,a,c);)if(b==c||!1===d||!(b=b.parentNode)||1!=b.nodeType)return;return b}var g="function"==typeof a?{matches:a}:this,l=b.bubble;return l?k(c,l(f),e):k(c,b,function(a){var b=f(a.target);return b&&e.call(b,a)})}};var a=[].slice,s=k.emit=function(b,d,c){var f=a.call(arguments,2),g="on"+d;if("parentNode"in b){var k=f[0]={},l;for(l in c)k[l]=c[l];k.preventDefault=m;k.stopPropagation=e;k.target=b;k.type=d;c=k}do b[g]&&b[g].apply(b,f);while(c&&c.bubbles&&(b=b.parentNode));return c&&
c.cancelable&&c},b=d("event-focusin")?{}:{focusin:"focus",focusout:"blur"};if(!d("event-stopimmediatepropagation"))var c=function(){this.modified=this.immediatelyStopped=!0},B=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=c,a.apply(this,arguments)}};if(d("dom-addeventlistener"))k.emit=function(a,b,d){if(a.dispatchEvent&&document.createEvent){var c=(a.ownerDocument||document).createEvent("HTMLEvents");c.initEvent(b,!!d.bubbles,!!d.cancelable);for(var e in d)e in
c||(c[e]=d[e]);return a.dispatchEvent(c)&&c}return s.apply(k,arguments)};else{k._fixEvent=function(a,b){a||(a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{C&&(a.type==C.type&&a.srcElement==C.target)&&(a=C)}catch(d){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=b||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=L,a.preventDefault=t),a.type){case "keypress":var c=
"charCode"in a?a.charCode:a.keyCode;10==c?(c=0,a.keyCode=13):13==c||27==c?c=0:3==c&&(c=99);a.charCode=c;c=a;c.keyChar=c.charCode?String.fromCharCode(c.charCode):"";c.charOrCode=c.keyChar||c.keyCode}return a};var C,r=function(a){this.handle=a};r.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var v=function(a){return function(b){b=k._fixEvent(b,this);var d=a.call(this,b);b.modified&&(C||setTimeout(function(){C=null}),C=b);return d}},u=function(a,b,c){c=v(c);if(((a.ownerDocument?
a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>d("jscript"))&&!d("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var e=a[b];if(!e||!e.listeners){var g=e,e=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");e.listeners=[];a[b]=e;e.global=this;g&&e.listeners.push(_dojoIEListeners_.push(g)-
1)}e.listeners.push(a=e.global._dojoIEListeners_.push(c)-1);return new r(a)}return f.after(a,b,c,!0)},L=function(){this.cancelBubble=!0},t=k._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(d("touch"))var w=function(){},x=window.orientation,Y=function(a){return function(b){var c=b.corrected;if(!c){var e=b.type;try{delete b.type}catch(f){}if(b.type){if(d("mozilla")){var c={},g;
for(g in b)c[g]=b[g]}else w.prototype=b,c=new w;c.preventDefault=function(){b.preventDefault()};c.stopPropagation=function(){b.stopPropagation()}}else c=b,c.type=e;b.corrected=c;if("resize"==e){if(x==window.orientation)return null;x=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var e=c.changedTouches[0],k;for(k in e)delete c[k],c[k]=e[k]}return a.call(this,c)}};return k})},"dojo/domReady":function(){define(["./has"],function(f){function p(a){g.push(a);
k&&d()}function d(){if(!a){for(a=!0;g.length;)try{g.shift()(m)}catch(b){}a=!1;p._onQEmpty()}}var l=this,m=document,e={loaded:1,complete:1},n="string"!=typeof m.readyState,k=!!e[m.readyState],g=[],a;p.load=function(a,b,c){p(c)};p._Q=g;p._onQEmpty=function(){};n&&(m.readyState="loading");if(!k){var s=[],b=function(a){a=a||l.event;k||"readystatechange"==a.type&&!e[m.readyState]||(n&&(m.readyState="complete"),k=1,d())},c=function(a,c){a.addEventListener(c,b,!1);g.push(function(){a.removeEventListener(c,
b,!1)})};if(!f("dom-addeventlistener")){var c=function(a,c){c="on"+c;a.attachEvent(c,b);g.push(function(){a.detachEvent(c,b)})},B=m.createElement("div");try{B.doScroll&&null===l.frameElement&&s.push(function(){try{return B.doScroll("left"),1}catch(a){}})}catch(C){}}c(m,"DOMContentLoaded");c(l,"load");"onreadystatechange"in m?c(m,"readystatechange"):n||s.push(function(){return e[m.readyState]});if(s.length){var r=function(){if(!k){for(var a=s.length;a--;)if(s[a]()){b("poller");return}setTimeout(r,
30)}};r()}}return p})},"dojo/ready":function(){define(["./_base/kernel","./has","require","./domReady","./_base/lang"],function(f,p,d,l,m){var e=0,n=[],k=0;p=function(){e=1;f._postLoad=f.config.afterOnLoad=!0;g()};var g=function(){if(!k){for(k=1;e&&(!l||0==l._Q.length)&&(d.idle?d.idle():1)&&n.length;){var a=n.shift();try{a()}catch(c){if(c.info=c.message,d.signal)d.signal("error",c);else throw c;}}k=0}};d.on&&d.on("idle",g);l&&(l._onQEmpty=g);var a=f.ready=f.addOnLoad=function(a,c,d){var e=m._toArray(arguments);
"number"!=typeof a?(d=c,c=a,a=1E3):e.shift();d=d?m.hitch.apply(f,e):function(){c()};d.priority=a;for(e=0;e<n.length&&a>=n[e].priority;e++);n.splice(e,0,d);g()},s=f.config.addOnLoad;if(s)a[m.isArray(s)?"apply":"call"](f,s);l?l(p):p();return a})},"dojo/promise/all":function(){define(["../_base/array","../Deferred","../when"],function(f,p,d){var l=f.some;return function(f){var e,n;f instanceof Array?n=f:f&&"object"===typeof f&&(e=f);var k,g=[];if(e){n=[];for(var a in e)Object.hasOwnProperty.call(e,a)&&
(g.push(a),n.push(e[a]));k={}}else n&&(k=[]);if(!n||!n.length)return(new p).resolve(k);var s=new p;s.promise.always(function(){k=g=null});var b=n.length;l(n,function(a,f){e||g.push(f);d(a,function(a){s.isFulfilled()||(k[g[f]]=a,0===--b&&s.resolve(k))},s.reject);return s.isFulfilled()});return s.promise}})}}});(function(){var f=this.require;f({cache:{}});!f.async&&f(["dojo"]);f.boot&&f.apply(null,f.boot)})();
//# sourceMappingURL=dojo.js.map